defmodule Burette.Color.En.Us do

  alias Burette.Helper.Lexicon

  @behaviour Burette.Color

  @names Lexicon.build [
    "Alice Blue",
    "Amber",
    "Amethyst",
    "Apricot",
    "Aqua",
    "Aquamarine",
    "Aspargus",
    "Azure",
    "Baby Blue",
    "Beige",
    "Blue",
    "Black",
    "Brass",
    "Brick Red",
    "Brown",
    "Camel",
    "Canary",
    "Capri",
    "Celadon",
    "Celeste",
    "Celestial Blue",
    "Cerulean",
    "Champagne",
    "Charcoal",
    "Cherry",
    "Chestnut",
    "Chocolate",
    "Cinnabar",
    "Citrine",
    "Cobalt",
    "Coffee",
    "Copper",
    "Coral",
    "Cream",
    "Crimson",
    "Cyan",
    "Daffodil",
    "Dandelion",
    "Dark Blue",
    "Dark Brown",
    "Dark Green",
    "Emerald",
    "Flamingo Pink",
    "Forest Green",
    "Fuchsia",
    "Gold",
    "Gray",
    "Green",
    "Indigo",
    "Ivory",
    "Jade",
    "Jasmine",
    "Jasper",
    "Khaki",
    "Lapis Lazuli",
    "Lava",
    "Lavender",
    "Lemon",
    "Lemon Chiffon",
    "Light Blue",
    "Light Gray",
    "Light Green",
    "Lilac",
    "Lime",
    "Lime Green",
    "Magenta",
    "Mahogany",
    "Maroon",
    "Mint",
    "Mustard",
    "Navy Blue",
    "Neon Fuchsia",
    "Neon Green",
    "Ochre",
    "Olive",
    "Onyx",
    "Orange",
    "Orchid",
    "Peach",
    "Pear",
    "Pearl",
    "Pink",
    "Pistachio",
    "Plum",
    "Pumpkin",
    "Purple",
    "Raspberry",
    "Red",
    "Royal Blue",
    "Salmon",
    "Sepia",
    "Snow",
    "Tan",
    "Teal",
    "Tomato",
    "Turquoise",
    "Vermilion",
    "Violet",
    "Viridian",
    "White",
    "Yellow"]

  def name do
    Lexicon.take(@names)
  end

  def lexicon do
    %{
      names: @names
    }
  end
end
